import asyncio
import json
import re

import httpx
from fastapi import APIRouter, Depends, HTTPException, Request, Response
from sse_starlette.sse import EventSourceResponse
from sqlmodel import Session

from app.core.db import get_session
from app.core.events import event_bus
from app.services import preview as preview_service
from app.services import project as project_service

router = APIRouter(prefix="/api/projects", tags=["preview"])


# ---------------------------------------------------------------------------
# Preview lifecycle
# ---------------------------------------------------------------------------

@router.post("/{project_id}/preview/start")
async def start_preview(
    project_id: str,
    session: Session = Depends(get_session),
):
    project = project_service.get_project(session, project_id)

    if project is None:
        raise HTTPException(status_code=404, detail="Project not found")

    row = await preview_service.start_preview(session, project)
    return row


@router.post("/{project_id}/preview/stop")
async def stop_preview(
    project_id: str,
    session: Session = Depends(get_session),
):
    project = project_service.get_project(session, project_id)

    if project is None:
        raise HTTPException(status_code=404, detail="Project not found")

    await preview_service.stop_preview(session, project_id)

    return {
        "status": "stopped",
        "project_id": project_id,
    }


@router.post("/{project_id}/preview/restart")
async def restart_preview(
    project_id: str,
    session: Session = Depends(get_session),
):
    project = project_service.get_project(session, project_id)

    if project is None:
        raise HTTPException(status_code=404, detail="Project not found")

    row = await preview_service.restart_preview(session, project)
    return row


@router.get("/{project_id}/preview")
def get_preview(
    project_id: str,
    session: Session = Depends(get_session),
):
    row = preview_service.get_preview(session, project_id)

    if row is None:
        raise HTTPException(
            status_code=404,
            detail="No preview for this project",
        )

    return row


# ---------------------------------------------------------------------------
# Preview proxy helpers
# ---------------------------------------------------------------------------

def _preview_prefix(project_id: str) -> str:
    return f"/api/projects/{project_id}/preview/view"


def _rewrite_preview_urls(
    text: str,
    project_id: str,
) -> str:
    """
    Rewrite URLs generated by Next.js so they go through our FastAPI
    preview proxy instead of directly trying to access localhost:3001+.
    """

    prefix = _preview_prefix(project_id)

    # ------------------------------------------------------------------
    # HTML attributes:
    # src="/..."
    # href="/..."
    # action="/..."
    # poster="/..."
    # formaction="/..."
    # ------------------------------------------------------------------

    pattern = re.compile(
        r'(?P<attr>\b(?:src|href|action|poster|formaction)\s*=\s*)'
        r'(?P<quote>["\'])'
        r'(?P<url>/[^"\']*)'
        r'(?P=endquote)',
        re.IGNORECASE,
    )

    def replace_attribute(match: re.Match) -> str:
        attr = match.group("attr")
        quote = match.group("quote")
        url = match.group("url")

        # Don't rewrite already proxied URLs.
        if url.startswith(prefix):
            return match.group(0)

        # Don't rewrite protocol-relative URLs.
        if url.startswith("//"):
            return match.group(0)

        # Don't rewrite API calls because generated applications may
        # intentionally use their own API paths.
        if url.startswith("/api/"):
            return match.group(0)

        return f"{attr}{quote}{prefix}{url}{quote}"

    text = pattern.sub(replace_attribute, text)

    # ------------------------------------------------------------------
    # CSS:
    # url(/image.png)
    # ------------------------------------------------------------------

    def replace_css_url(match: re.Match) -> str:
        url = match.group(1).strip()

        if (
            not url.startswith("/")
            or url.startswith("//")
            or url.startswith(prefix)
            or url.startswith("/api/")
        ):
            return match.group(0)

        return f"url({prefix}{url})"

    text = re.sub(
        r"url\(\s*([^)]+)\s*\)",
        replace_css_url,
        text,
        flags=re.IGNORECASE,
    )

    # ------------------------------------------------------------------
    # Next.js special assets
    #
    # /_next/...
    # ------------------------------------------------------------------

    text = re.sub(
        r'(["\'(])/_next/',
        rf'\1{prefix}/_next/',
        text,
    )

    # Avoid accidentally double-prefixing.
    text = text.replace(
        f"{prefix}{prefix}",
        prefix,
    )

    # ------------------------------------------------------------------
    # Inject a small browser-side URL helper.
    #
    # This handles fetch/XHR/history calls that use root-relative URLs.
    # ------------------------------------------------------------------

    bootstrap = f"""
<script>
(function() {{
    const PREVIEW_PREFIX = {json.dumps(prefix)};

    function rewriteUrl(input) {{
        if (typeof input !== "string") {{
            return input;
        }}

        if (
            input.startsWith(PREVIEW_PREFIX) ||
            input.startsWith("http://") ||
            input.startsWith("https://") ||
            input.startsWith("//") ||
            input.startsWith("data:") ||
            input.startsWith("blob:") ||
            input.startsWith("#")
        ) {{
            return input;
        }}

        if (input.startsWith("/api/")) {{
            return input;
        }}

        if (input.startsWith("/")) {{
            return PREVIEW_PREFIX + input;
        }}

        return input;
    }}

    const originalFetch = window.fetch;

    window.fetch = function(input, init) {{
        try {{
            if (typeof input === "string") {{
                input = rewriteUrl(input);
            }} else if (input instanceof Request) {{
                const rewritten = rewriteUrl(input.url);

                if (rewritten !== input.url) {{
                    input = new Request(rewritten, input);
                }}
            }}
        }} catch (e) {{
            console.debug("Preview fetch rewrite failed", e);
        }}

        return originalFetch.call(this, input, init);
    }};

    const OriginalXHR = window.XMLHttpRequest;

    window.XMLHttpRequest = function() {{
        const xhr = new OriginalXHR();

        const originalOpen = xhr.open;

        xhr.open = function(method, url, ...args) {{
            try {{
                url = rewriteUrl(url);
            }} catch (e) {{
                console.debug("Preview XHR rewrite failed", e);
            }}

            return originalOpen.call(this, method, url, ...args);
        }};

        return xhr;
    }};

    const originalPushState = history.pushState;

    history.pushState = function(state, title, url) {{
        if (typeof url === "string") {{
            url = rewriteUrl(url);
        }}

        return originalPushState.call(this, state, title, url);
    }};

    const originalReplaceState = history.replaceState;

    history.replaceState = function(state, title, url) {{
        if (typeof url === "string") {{
            url = rewriteUrl(url);
        }}

        return originalReplaceState.call(this, state, title, url);
    }};
}})();
</script>
"""

    # Inject before </head> when possible.
    if "</head>" in text.lower():
        text = re.sub(
            r"</head>",
            bootstrap + "\n</head>",
            text,
            count=1,
            flags=re.IGNORECASE,
        )
    else:
        text = bootstrap + text

    return text


# ---------------------------------------------------------------------------
# Preview proxy
# ---------------------------------------------------------------------------

async def _proxy_preview(
    project_id: str,
    path: str,
    request: Request,
    session: Session,
) -> Response:

    row = preview_service.get_preview(session, project_id)

    if row is None:
        raise HTTPException(
            status_code=404,
            detail="No preview for this project",
        )

    if row.port is None:
        raise HTTPException(
            status_code=503,
            detail="Preview has no assigned port",
        )

    if not preview_service.is_preview_running(project_id):
        raise HTTPException(
            status_code=503,
            detail="Preview server is not running",
        )

    # Remove accidental leading slash.
    path = path.lstrip("/")

    target_url = f"http://127.0.0.1:{row.port}/{path}"

    # Preserve query parameters.
    query_string = request.url.query

    if query_string:
        target_url = f"{target_url}?{query_string}"

    try:
        async with httpx.AsyncClient(
            timeout=30.0,
            follow_redirects=False,
        ) as client:

            upstream = await client.request(
                method=request.method,
                url=target_url,
                headers={
                    key: value
                    for key, value in request.headers.items()
                    if key.lower()
                    not in {
                        "host",
                        "content-length",
                        "connection",
                    }
                },
                content=await request.body(),
            )

    except httpx.ConnectError:
        raise HTTPException(
            status_code=502,
            detail="Unable to connect to preview server",
        )

    except httpx.TimeoutException:
        raise HTTPException(
            status_code=504,
            detail="Preview server request timed out",
        )

    except httpx.HTTPError as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Preview proxy error: {type(exc).__name__}",
        )

    content = upstream.content

    content_type = upstream.headers.get(
        "content-type",
        "",
    ).lower()

    # ---------------------------------------------------------------
    # Rewrite HTML responses.
    # ---------------------------------------------------------------

    if "text/html" in content_type:
        try:
            text = content.decode(
                upstream.encoding or "utf-8",
                errors="replace",
            )

            text = _rewrite_preview_urls(
                text,
                project_id,
            )

            content = text.encode("utf-8")

            response_headers = {
                key: value
                for key, value in upstream.headers.items()
                if key.lower()
                not in {
                    "content-length",
                    "content-encoding",
                    "transfer-encoding",
                }
            }

            response_headers["content-type"] = "text/html; charset=utf-8"

        except Exception:
            response_headers = {
                key: value
                for key, value in upstream.headers.items()
                if key.lower()
                not in {
                    "content-length",
                    "content-encoding",
                    "transfer-encoding",
                }
            }

    else:
        response_headers = {
            key: value
            for key, value in upstream.headers.items()
            if key.lower()
            not in {
                "content-length",
                "content-encoding",
                "transfer-encoding",
                "connection",
            }
        }

    return Response(
        content=content,
        status_code=upstream.status_code,
        headers=response_headers,
        media_type=None,
    )


# ---------------------------------------------------------------------------
# Preview root
# ---------------------------------------------------------------------------

@router.get("/{project_id}/preview/view")
async def preview_view_root(
    project_id: str,
    request: Request,
    session: Session = Depends(get_session),
):
    return await _proxy_preview(
        project_id=project_id,
        path="",
        request=request,
        session=session,
    )


# ---------------------------------------------------------------------------
# Preview catch-all
#
# Examples:
#
# /preview/view/_next/static/...
# /preview/view/assets/logo.png
# /preview/view/about
# /preview/view/api/...
# ---------------------------------------------------------------------------

@router.api_route(
    "/{project_id}/preview/view/{path:path}",
    methods=[
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE",
        "OPTIONS",
        "HEAD",
    ],
)
async def preview_view(
    project_id: str,
    path: str,
    request: Request,
    session: Session = Depends(get_session),
):
    return await _proxy_preview(
        project_id=project_id,
        path=path,
        request=request,
        session=session,
    )


# ---------------------------------------------------------------------------
# Server-Sent Events
# ---------------------------------------------------------------------------

@router.get("/{project_id}/events")
async def events(project_id: str):
    queue = event_bus.subscribe(project_id)

    async def event_generator():
        try:
            while True:
                payload = await queue.get()

                try:
                    data = json.loads(payload)
                except json.JSONDecodeError:
                    data = {
                        "type": "message",
                        "data": payload,
                    }

                yield {
                    "event": data.get("type", "message"),
                    "data": json.dumps(data),
                }

        except asyncio.CancelledError:
            pass

        finally:
            event_bus.unsubscribe(
                project_id,
                queue,
            )

    return EventSourceResponse(event_generator())
